//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18408 版自动生成。
// 
#pragma warning disable 1591

namespace AdvanceSub.cn.com.sngoo.app8 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="databaseSoap", Namespace="http://app8.sngoo.com.cn/")]
    public partial class database : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifyPassWordOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifyUserRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPickPointListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGoodsOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback getALLGoodsOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGoodsOrderInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback alterAddvanceSubStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteIntoSubOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadSubInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterSubStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteSubInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InputAssociationListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOrderListOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterGoodsOderStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGoodsOrderListByAddvanceIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback alterGoodsOrderShoppingStateOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteShoppingNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGoodsClassOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBoxInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public database() {
            this.Url = global::AdvanceSub.Properties.Settings.Default.AdvanceSub_cn_com_sngoo_app8_database;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event verifyPassWordCompletedEventHandler verifyPassWordCompleted;
        
        /// <remarks/>
        public event verifyUserRoleCompletedEventHandler verifyUserRoleCompleted;
        
        /// <remarks/>
        public event getPickPointListCompletedEventHandler getPickPointListCompleted;
        
        /// <remarks/>
        public event getGoodsOrderCompletedEventHandler getGoodsOrderCompleted;
        
        /// <remarks/>
        public event getALLGoodsOrderCompletedEventHandler getALLGoodsOrderCompleted;
        
        /// <remarks/>
        public event getGoodsOrderInfoCompletedEventHandler getGoodsOrderInfoCompleted;
        
        /// <remarks/>
        public event alterAddvanceSubStatusCompletedEventHandler alterAddvanceSubStatusCompleted;
        
        /// <remarks/>
        public event WriteIntoSubCompletedEventHandler WriteIntoSubCompleted;
        
        /// <remarks/>
        public event ReadSubInfoCompletedEventHandler ReadSubInfoCompleted;
        
        /// <remarks/>
        public event AlterSubStatusCompletedEventHandler AlterSubStatusCompleted;
        
        /// <remarks/>
        public event DeleteSubInfoCompletedEventHandler DeleteSubInfoCompleted;
        
        /// <remarks/>
        public event InputAssociationListCompletedEventHandler InputAssociationListCompleted;
        
        /// <remarks/>
        public event getOrderListCompletedEventHandler getOrderListCompleted;
        
        /// <remarks/>
        public event AlterGoodsOderStatusCompletedEventHandler AlterGoodsOderStatusCompleted;
        
        /// <remarks/>
        public event getGoodsOrderListByAddvanceIdCompletedEventHandler getGoodsOrderListByAddvanceIdCompleted;
        
        /// <remarks/>
        public event alterGoodsOrderShoppingStateCompletedEventHandler alterGoodsOrderShoppingStateCompleted;
        
        /// <remarks/>
        public event WriteShoppingNoCompletedEventHandler WriteShoppingNoCompleted;
        
        /// <remarks/>
        public event GetGoodsClassCompletedEventHandler GetGoodsClassCompleted;
        
        /// <remarks/>
        public event GetBoxInfoCompletedEventHandler GetBoxInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/HelloWorld", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/verifyPassWord", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool verifyPassWord(string id, string ps) {
            object[] results = this.Invoke("verifyPassWord", new object[] {
                        id,
                        ps});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void verifyPassWordAsync(string id, string ps) {
            this.verifyPassWordAsync(id, ps, null);
        }
        
        /// <remarks/>
        public void verifyPassWordAsync(string id, string ps, object userState) {
            if ((this.verifyPassWordOperationCompleted == null)) {
                this.verifyPassWordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifyPassWordOperationCompleted);
            }
            this.InvokeAsync("verifyPassWord", new object[] {
                        id,
                        ps}, this.verifyPassWordOperationCompleted, userState);
        }
        
        private void OnverifyPassWordOperationCompleted(object arg) {
            if ((this.verifyPassWordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifyPassWordCompleted(this, new verifyPassWordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/verifyUserRole", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool verifyUserRole(string id) {
            object[] results = this.Invoke("verifyUserRole", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void verifyUserRoleAsync(string id) {
            this.verifyUserRoleAsync(id, null);
        }
        
        /// <remarks/>
        public void verifyUserRoleAsync(string id, object userState) {
            if ((this.verifyUserRoleOperationCompleted == null)) {
                this.verifyUserRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifyUserRoleOperationCompleted);
            }
            this.InvokeAsync("verifyUserRole", new object[] {
                        id}, this.verifyUserRoleOperationCompleted, userState);
        }
        
        private void OnverifyUserRoleOperationCompleted(object arg) {
            if ((this.verifyUserRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifyUserRoleCompleted(this, new verifyUserRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/getPickPointList", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getPickPointList() {
            object[] results = this.Invoke("getPickPointList", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getPickPointListAsync() {
            this.getPickPointListAsync(null);
        }
        
        /// <remarks/>
        public void getPickPointListAsync(object userState) {
            if ((this.getPickPointListOperationCompleted == null)) {
                this.getPickPointListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPickPointListOperationCompleted);
            }
            this.InvokeAsync("getPickPointList", new object[0], this.getPickPointListOperationCompleted, userState);
        }
        
        private void OngetPickPointListOperationCompleted(object arg) {
            if ((this.getPickPointListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPickPointListCompleted(this, new getPickPointListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/getGoodsOrder", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GoodsOrder[] getGoodsOrder(string PickPoint, System.DateTime starTime, System.DateTime endTime) {
            object[] results = this.Invoke("getGoodsOrder", new object[] {
                        PickPoint,
                        starTime,
                        endTime});
            return ((GoodsOrder[])(results[0]));
        }
        
        /// <remarks/>
        public void getGoodsOrderAsync(string PickPoint, System.DateTime starTime, System.DateTime endTime) {
            this.getGoodsOrderAsync(PickPoint, starTime, endTime, null);
        }
        
        /// <remarks/>
        public void getGoodsOrderAsync(string PickPoint, System.DateTime starTime, System.DateTime endTime, object userState) {
            if ((this.getGoodsOrderOperationCompleted == null)) {
                this.getGoodsOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGoodsOrderOperationCompleted);
            }
            this.InvokeAsync("getGoodsOrder", new object[] {
                        PickPoint,
                        starTime,
                        endTime}, this.getGoodsOrderOperationCompleted, userState);
        }
        
        private void OngetGoodsOrderOperationCompleted(object arg) {
            if ((this.getGoodsOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGoodsOrderCompleted(this, new getGoodsOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/getALLGoodsOrder", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GoodsOrder[] getALLGoodsOrder(System.DateTime starTime, System.DateTime endTime) {
            object[] results = this.Invoke("getALLGoodsOrder", new object[] {
                        starTime,
                        endTime});
            return ((GoodsOrder[])(results[0]));
        }
        
        /// <remarks/>
        public void getALLGoodsOrderAsync(System.DateTime starTime, System.DateTime endTime) {
            this.getALLGoodsOrderAsync(starTime, endTime, null);
        }
        
        /// <remarks/>
        public void getALLGoodsOrderAsync(System.DateTime starTime, System.DateTime endTime, object userState) {
            if ((this.getALLGoodsOrderOperationCompleted == null)) {
                this.getALLGoodsOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetALLGoodsOrderOperationCompleted);
            }
            this.InvokeAsync("getALLGoodsOrder", new object[] {
                        starTime,
                        endTime}, this.getALLGoodsOrderOperationCompleted, userState);
        }
        
        private void OngetALLGoodsOrderOperationCompleted(object arg) {
            if ((this.getALLGoodsOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getALLGoodsOrderCompleted(this, new getALLGoodsOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/getGoodsOrderInfo", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GoodsOrderInfo[] getGoodsOrderInfo(string GoodsNo) {
            object[] results = this.Invoke("getGoodsOrderInfo", new object[] {
                        GoodsNo});
            return ((GoodsOrderInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void getGoodsOrderInfoAsync(string GoodsNo) {
            this.getGoodsOrderInfoAsync(GoodsNo, null);
        }
        
        /// <remarks/>
        public void getGoodsOrderInfoAsync(string GoodsNo, object userState) {
            if ((this.getGoodsOrderInfoOperationCompleted == null)) {
                this.getGoodsOrderInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGoodsOrderInfoOperationCompleted);
            }
            this.InvokeAsync("getGoodsOrderInfo", new object[] {
                        GoodsNo}, this.getGoodsOrderInfoOperationCompleted, userState);
        }
        
        private void OngetGoodsOrderInfoOperationCompleted(object arg) {
            if ((this.getGoodsOrderInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGoodsOrderInfoCompleted(this, new getGoodsOrderInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/alterAddvanceSubStatus", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void alterAddvanceSubStatus(string GoodsNo, string Status) {
            this.Invoke("alterAddvanceSubStatus", new object[] {
                        GoodsNo,
                        Status});
        }
        
        /// <remarks/>
        public void alterAddvanceSubStatusAsync(string GoodsNo, string Status) {
            this.alterAddvanceSubStatusAsync(GoodsNo, Status, null);
        }
        
        /// <remarks/>
        public void alterAddvanceSubStatusAsync(string GoodsNo, string Status, object userState) {
            if ((this.alterAddvanceSubStatusOperationCompleted == null)) {
                this.alterAddvanceSubStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalterAddvanceSubStatusOperationCompleted);
            }
            this.InvokeAsync("alterAddvanceSubStatus", new object[] {
                        GoodsNo,
                        Status}, this.alterAddvanceSubStatusOperationCompleted, userState);
        }
        
        private void OnalterAddvanceSubStatusOperationCompleted(object arg) {
            if ((this.alterAddvanceSubStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alterAddvanceSubStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/WriteIntoSub", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WriteIntoSub(AddvanceSubInfo info) {
            this.Invoke("WriteIntoSub", new object[] {
                        info});
        }
        
        /// <remarks/>
        public void WriteIntoSubAsync(AddvanceSubInfo info) {
            this.WriteIntoSubAsync(info, null);
        }
        
        /// <remarks/>
        public void WriteIntoSubAsync(AddvanceSubInfo info, object userState) {
            if ((this.WriteIntoSubOperationCompleted == null)) {
                this.WriteIntoSubOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteIntoSubOperationCompleted);
            }
            this.InvokeAsync("WriteIntoSub", new object[] {
                        info}, this.WriteIntoSubOperationCompleted, userState);
        }
        
        private void OnWriteIntoSubOperationCompleted(object arg) {
            if ((this.WriteIntoSubCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteIntoSubCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/ReadSubInfo", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AddvanceSubInfo[] ReadSubInfo() {
            object[] results = this.Invoke("ReadSubInfo", new object[0]);
            return ((AddvanceSubInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadSubInfoAsync() {
            this.ReadSubInfoAsync(null);
        }
        
        /// <remarks/>
        public void ReadSubInfoAsync(object userState) {
            if ((this.ReadSubInfoOperationCompleted == null)) {
                this.ReadSubInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadSubInfoOperationCompleted);
            }
            this.InvokeAsync("ReadSubInfo", new object[0], this.ReadSubInfoOperationCompleted, userState);
        }
        
        private void OnReadSubInfoOperationCompleted(object arg) {
            if ((this.ReadSubInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadSubInfoCompleted(this, new ReadSubInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/AlterSubStatus", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterSubStatus(int Status, int id) {
            this.Invoke("AlterSubStatus", new object[] {
                        Status,
                        id});
        }
        
        /// <remarks/>
        public void AlterSubStatusAsync(int Status, int id) {
            this.AlterSubStatusAsync(Status, id, null);
        }
        
        /// <remarks/>
        public void AlterSubStatusAsync(int Status, int id, object userState) {
            if ((this.AlterSubStatusOperationCompleted == null)) {
                this.AlterSubStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterSubStatusOperationCompleted);
            }
            this.InvokeAsync("AlterSubStatus", new object[] {
                        Status,
                        id}, this.AlterSubStatusOperationCompleted, userState);
        }
        
        private void OnAlterSubStatusOperationCompleted(object arg) {
            if ((this.AlterSubStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterSubStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/DeleteSubInfo", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteSubInfo(int id) {
            this.Invoke("DeleteSubInfo", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void DeleteSubInfoAsync(int id) {
            this.DeleteSubInfoAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteSubInfoAsync(int id, object userState) {
            if ((this.DeleteSubInfoOperationCompleted == null)) {
                this.DeleteSubInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteSubInfoOperationCompleted);
            }
            this.InvokeAsync("DeleteSubInfo", new object[] {
                        id}, this.DeleteSubInfoOperationCompleted, userState);
        }
        
        private void OnDeleteSubInfoOperationCompleted(object arg) {
            if ((this.DeleteSubInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteSubInfoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/InputAssociationList", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InputAssociationList(string[] list, string id) {
            this.Invoke("InputAssociationList", new object[] {
                        list,
                        id});
        }
        
        /// <remarks/>
        public void InputAssociationListAsync(string[] list, string id) {
            this.InputAssociationListAsync(list, id, null);
        }
        
        /// <remarks/>
        public void InputAssociationListAsync(string[] list, string id, object userState) {
            if ((this.InputAssociationListOperationCompleted == null)) {
                this.InputAssociationListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInputAssociationListOperationCompleted);
            }
            this.InvokeAsync("InputAssociationList", new object[] {
                        list,
                        id}, this.InputAssociationListOperationCompleted, userState);
        }
        
        private void OnInputAssociationListOperationCompleted(object arg) {
            if ((this.InputAssociationListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InputAssociationListCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/getOrderList", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getOrderList(string AddvanceId) {
            object[] results = this.Invoke("getOrderList", new object[] {
                        AddvanceId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getOrderListAsync(string AddvanceId) {
            this.getOrderListAsync(AddvanceId, null);
        }
        
        /// <remarks/>
        public void getOrderListAsync(string AddvanceId, object userState) {
            if ((this.getOrderListOperationCompleted == null)) {
                this.getOrderListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrderListOperationCompleted);
            }
            this.InvokeAsync("getOrderList", new object[] {
                        AddvanceId}, this.getOrderListOperationCompleted, userState);
        }
        
        private void OngetOrderListOperationCompleted(object arg) {
            if ((this.getOrderListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrderListCompleted(this, new getOrderListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/AlterGoodsOderStatus", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterGoodsOderStatus(int Status, string[] GoodsOrder) {
            this.Invoke("AlterGoodsOderStatus", new object[] {
                        Status,
                        GoodsOrder});
        }
        
        /// <remarks/>
        public void AlterGoodsOderStatusAsync(int Status, string[] GoodsOrder) {
            this.AlterGoodsOderStatusAsync(Status, GoodsOrder, null);
        }
        
        /// <remarks/>
        public void AlterGoodsOderStatusAsync(int Status, string[] GoodsOrder, object userState) {
            if ((this.AlterGoodsOderStatusOperationCompleted == null)) {
                this.AlterGoodsOderStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterGoodsOderStatusOperationCompleted);
            }
            this.InvokeAsync("AlterGoodsOderStatus", new object[] {
                        Status,
                        GoodsOrder}, this.AlterGoodsOderStatusOperationCompleted, userState);
        }
        
        private void OnAlterGoodsOderStatusOperationCompleted(object arg) {
            if ((this.AlterGoodsOderStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterGoodsOderStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/getGoodsOrderListByAddvanceId", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GoodsOrder[] getGoodsOrderListByAddvanceId(string[] list) {
            object[] results = this.Invoke("getGoodsOrderListByAddvanceId", new object[] {
                        list});
            return ((GoodsOrder[])(results[0]));
        }
        
        /// <remarks/>
        public void getGoodsOrderListByAddvanceIdAsync(string[] list) {
            this.getGoodsOrderListByAddvanceIdAsync(list, null);
        }
        
        /// <remarks/>
        public void getGoodsOrderListByAddvanceIdAsync(string[] list, object userState) {
            if ((this.getGoodsOrderListByAddvanceIdOperationCompleted == null)) {
                this.getGoodsOrderListByAddvanceIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGoodsOrderListByAddvanceIdOperationCompleted);
            }
            this.InvokeAsync("getGoodsOrderListByAddvanceId", new object[] {
                        list}, this.getGoodsOrderListByAddvanceIdOperationCompleted, userState);
        }
        
        private void OngetGoodsOrderListByAddvanceIdOperationCompleted(object arg) {
            if ((this.getGoodsOrderListByAddvanceIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGoodsOrderListByAddvanceIdCompleted(this, new getGoodsOrderListByAddvanceIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/alterGoodsOrderShoppingState", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void alterGoodsOrderShoppingState(int Status, string[] GoodsOrder) {
            this.Invoke("alterGoodsOrderShoppingState", new object[] {
                        Status,
                        GoodsOrder});
        }
        
        /// <remarks/>
        public void alterGoodsOrderShoppingStateAsync(int Status, string[] GoodsOrder) {
            this.alterGoodsOrderShoppingStateAsync(Status, GoodsOrder, null);
        }
        
        /// <remarks/>
        public void alterGoodsOrderShoppingStateAsync(int Status, string[] GoodsOrder, object userState) {
            if ((this.alterGoodsOrderShoppingStateOperationCompleted == null)) {
                this.alterGoodsOrderShoppingStateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalterGoodsOrderShoppingStateOperationCompleted);
            }
            this.InvokeAsync("alterGoodsOrderShoppingState", new object[] {
                        Status,
                        GoodsOrder}, this.alterGoodsOrderShoppingStateOperationCompleted, userState);
        }
        
        private void OnalterGoodsOrderShoppingStateOperationCompleted(object arg) {
            if ((this.alterGoodsOrderShoppingStateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alterGoodsOrderShoppingStateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/WriteShoppingNo", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WriteShoppingNo(string No, string GoodsNo) {
            this.Invoke("WriteShoppingNo", new object[] {
                        No,
                        GoodsNo});
        }
        
        /// <remarks/>
        public void WriteShoppingNoAsync(string No, string GoodsNo) {
            this.WriteShoppingNoAsync(No, GoodsNo, null);
        }
        
        /// <remarks/>
        public void WriteShoppingNoAsync(string No, string GoodsNo, object userState) {
            if ((this.WriteShoppingNoOperationCompleted == null)) {
                this.WriteShoppingNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteShoppingNoOperationCompleted);
            }
            this.InvokeAsync("WriteShoppingNo", new object[] {
                        No,
                        GoodsNo}, this.WriteShoppingNoOperationCompleted, userState);
        }
        
        private void OnWriteShoppingNoOperationCompleted(object arg) {
            if ((this.WriteShoppingNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteShoppingNoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/GetGoodsClass", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetGoodsClass() {
            object[] results = this.Invoke("GetGoodsClass", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGoodsClassAsync() {
            this.GetGoodsClassAsync(null);
        }
        
        /// <remarks/>
        public void GetGoodsClassAsync(object userState) {
            if ((this.GetGoodsClassOperationCompleted == null)) {
                this.GetGoodsClassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGoodsClassOperationCompleted);
            }
            this.InvokeAsync("GetGoodsClass", new object[0], this.GetGoodsClassOperationCompleted, userState);
        }
        
        private void OnGetGoodsClassOperationCompleted(object arg) {
            if ((this.GetGoodsClassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGoodsClassCompleted(this, new GetGoodsClassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://app8.sngoo.com.cn/GetBoxInfo", RequestNamespace="http://app8.sngoo.com.cn/", ResponseNamespace="http://app8.sngoo.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BoxInfo GetBoxInfo(string GoodsNo) {
            object[] results = this.Invoke("GetBoxInfo", new object[] {
                        GoodsNo});
            return ((BoxInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetBoxInfoAsync(string GoodsNo) {
            this.GetBoxInfoAsync(GoodsNo, null);
        }
        
        /// <remarks/>
        public void GetBoxInfoAsync(string GoodsNo, object userState) {
            if ((this.GetBoxInfoOperationCompleted == null)) {
                this.GetBoxInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBoxInfoOperationCompleted);
            }
            this.InvokeAsync("GetBoxInfo", new object[] {
                        GoodsNo}, this.GetBoxInfoOperationCompleted, userState);
        }
        
        private void OnGetBoxInfoOperationCompleted(object arg) {
            if ((this.GetBoxInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBoxInfoCompleted(this, new GetBoxInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://app8.sngoo.com.cn/")]
    public partial class GoodsOrder {
        
        private string orderNoField;
        
        private System.DateTime payTimeField;
        
        private string pickPointNameField;
        
        private string recevieNameField;
        
        private string receiveTelField;
        
        private byte addvanceSubField;
        
        private string pickCodeField;
        
        private string recoCodeField;
        
        private string shoppingNoField;
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PayTime {
            get {
                return this.payTimeField;
            }
            set {
                this.payTimeField = value;
            }
        }
        
        /// <remarks/>
        public string PickPointName {
            get {
                return this.pickPointNameField;
            }
            set {
                this.pickPointNameField = value;
            }
        }
        
        /// <remarks/>
        public string RecevieName {
            get {
                return this.recevieNameField;
            }
            set {
                this.recevieNameField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiveTel {
            get {
                return this.receiveTelField;
            }
            set {
                this.receiveTelField = value;
            }
        }
        
        /// <remarks/>
        public byte AddvanceSub {
            get {
                return this.addvanceSubField;
            }
            set {
                this.addvanceSubField = value;
            }
        }
        
        /// <remarks/>
        public string PickCode {
            get {
                return this.pickCodeField;
            }
            set {
                this.pickCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RecoCode {
            get {
                return this.recoCodeField;
            }
            set {
                this.recoCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ShoppingNo {
            get {
                return this.shoppingNoField;
            }
            set {
                this.shoppingNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://app8.sngoo.com.cn/")]
    public partial class BoxInfo {
        
        private string boxIdField;
        
        private string orderNumField;
        
        private string boxGroupIdField;
        
        private string boxGroupOpenCodeField;
        
        private int sendStateField;
        
        /// <remarks/>
        public string BoxId {
            get {
                return this.boxIdField;
            }
            set {
                this.boxIdField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNum {
            get {
                return this.orderNumField;
            }
            set {
                this.orderNumField = value;
            }
        }
        
        /// <remarks/>
        public string BoxGroupId {
            get {
                return this.boxGroupIdField;
            }
            set {
                this.boxGroupIdField = value;
            }
        }
        
        /// <remarks/>
        public string BoxGroupOpenCode {
            get {
                return this.boxGroupOpenCodeField;
            }
            set {
                this.boxGroupOpenCodeField = value;
            }
        }
        
        /// <remarks/>
        public int SendState {
            get {
                return this.sendStateField;
            }
            set {
                this.sendStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://app8.sngoo.com.cn/")]
    public partial class AddvanceSubInfo {
        
        private int idField;
        
        private int orderNumField;
        
        private System.DateTime countTimeField;
        
        private string detailsField;
        
        private int addvanceSubStateField;
        
        private string addvanceIdField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int OrderNum {
            get {
                return this.orderNumField;
            }
            set {
                this.orderNumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CountTime {
            get {
                return this.countTimeField;
            }
            set {
                this.countTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        public int AddvanceSubState {
            get {
                return this.addvanceSubStateField;
            }
            set {
                this.addvanceSubStateField = value;
            }
        }
        
        /// <remarks/>
        public string AddvanceId {
            get {
                return this.addvanceIdField;
            }
            set {
                this.addvanceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://app8.sngoo.com.cn/")]
    public partial class GoodsOrderInfo {
        
        private string goodsNameField;
        
        private int goodsNumField;
        
        /// <remarks/>
        public string GoodsName {
            get {
                return this.goodsNameField;
            }
            set {
                this.goodsNameField = value;
            }
        }
        
        /// <remarks/>
        public int GoodsNum {
            get {
                return this.goodsNumField;
            }
            set {
                this.goodsNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void verifyPassWordCompletedEventHandler(object sender, verifyPassWordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifyPassWordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifyPassWordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void verifyUserRoleCompletedEventHandler(object sender, verifyUserRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifyUserRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifyUserRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getPickPointListCompletedEventHandler(object sender, getPickPointListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPickPointListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPickPointListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getGoodsOrderCompletedEventHandler(object sender, getGoodsOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGoodsOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGoodsOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GoodsOrder[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GoodsOrder[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getALLGoodsOrderCompletedEventHandler(object sender, getALLGoodsOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getALLGoodsOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getALLGoodsOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GoodsOrder[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GoodsOrder[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getGoodsOrderInfoCompletedEventHandler(object sender, getGoodsOrderInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGoodsOrderInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGoodsOrderInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GoodsOrderInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GoodsOrderInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void alterAddvanceSubStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WriteIntoSubCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReadSubInfoCompletedEventHandler(object sender, ReadSubInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadSubInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadSubInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddvanceSubInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddvanceSubInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AlterSubStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteSubInfoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void InputAssociationListCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getOrderListCompletedEventHandler(object sender, getOrderListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOrderListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOrderListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AlterGoodsOderStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getGoodsOrderListByAddvanceIdCompletedEventHandler(object sender, getGoodsOrderListByAddvanceIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGoodsOrderListByAddvanceIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGoodsOrderListByAddvanceIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GoodsOrder[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GoodsOrder[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void alterGoodsOrderShoppingStateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WriteShoppingNoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGoodsClassCompletedEventHandler(object sender, GetGoodsClassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGoodsClassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGoodsClassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetBoxInfoCompletedEventHandler(object sender, GetBoxInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBoxInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBoxInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BoxInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BoxInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591